# Generated by Django 2.2.5 on 2020-09-27 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('student', 'Student'), ('seller', 'Seller')], max_length=50)),
                ('student', models.BooleanField(default=False, editable=False)),
                ('landLord', models.BooleanField(default=False, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_landlord', 'User is a landlord'), ('is_student', 'User is a Student')),
            },
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('isCollegeStudent', models.BooleanField(default=False)),
                ('collegeName', models.CharField(blank=True, max_length=150)),
                ('profilePicture', models.ImageField(blank=True, upload_to=users.models.profile_image_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserType')),
            ],
        ),
        migrations.CreateModel(
            name='UserLandLord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('profilePicture', models.ImageField(blank=True, upload_to=users.models.profile_image_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserType')),
            ],
        ),
    ]
