# Generated by Django 2.2.5 on 2020-09-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={},
        ),
    ]
