# Generated by Django 2.2.5 on 2020-09-15 15:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuyer',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=users.models.profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='userlandlord',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=users.models.profile_image_file_path),
        ),
    ]
