# Generated by Django 2.2.5 on 2020-08-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='user_id',
            new_name='l_id',
        ),
    ]
