# Generated by Django 2.2.5 on 2020-09-30 18:11

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200927_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(help_text='Type of Interest. eg Partying, Sports etc', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userlandlord',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='userstudent',
            name='collegeName',
        ),
        migrations.RemoveField(
            model_name='userstudent',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='userstudent',
            name='isCollegeStudent',
        ),
        migrations.AddField(
            model_name='userlandlord',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 30, 18, 10, 25, 738250, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlandlord',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlandlord',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+41524204242", max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlandlord',
            name='phoneVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='bio',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='classYear',
            field=models.IntegerField(default=202),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="1231", max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='phoneVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='university',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlandlord',
            name='profilePicture',
            field=models.ImageField(upload_to=users.models.profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='profilePicture',
            field=models.ImageField(upload_to=users.models.profile_image_file_path),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='interests',
            field=models.ManyToManyField(to='users.Interest'),
        ),
    ]
