# Generated by Django 2.2.5 on 2020-08-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200828_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='landlord',
            name='38f03723',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='46f4c024',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
