# Generated by Django 2.2.5 on 2020-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200930_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='fbLink',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='instaLink',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='redditLink',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='snapLink',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
