# Generated by Django 2.2.5 on 2020-08-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200828_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='38f03723',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='46f4c024',
            new_name='profile_picture',
        ),
    ]
