# Generated by Django 2.2.5 on 2020-09-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='userType',
            field=models.CharField(choices=[('Buyer', 'buyer'), ('Seller', 'seller')], default='buyer', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbuyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserType'),
        ),
        migrations.AlterField(
            model_name='userlandlord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserType'),
        ),
    ]
