# Generated by Django 2.2.5 on 2020-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201005_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='fbLink',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='instaLink',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='redditLink',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='snapLink',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
