# Generated by Django 2.2.5 on 2020-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200917_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBuyer',
            new_name='UserStudent',
        ),
        migrations.RenameField(
            model_name='userstudent',
            old_name='isStudent',
            new_name='isCollegeStudent',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='buyer',
        ),
        migrations.AddField(
            model_name='usertype',
            name='student',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='landLord',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='userType',
            field=models.CharField(choices=[('student', 'Student'), ('seller', 'Seller')], max_length=50),
        ),
    ]
