# Generated by Django 2.2.5 on 2020-10-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0006_auto_20201005_1035'),
        ('users', '0005_auto_20201005_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.ManyToManyField(to='property.Property')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='users.UserStudent')),
            ],
        ),
    ]
