# Generated by Django 2.2.5 on 2020-12-10 18:14

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=students.models.roompost_image_file_path)),
                ('image1', models.ImageField(blank=True, upload_to=students.models.roompost_image_file_path)),
                ('image2', models.ImageField(blank=True, upload_to=students.models.roompost_image_file_path)),
                ('image3', models.ImageField(blank=True, upload_to=students.models.roompost_image_file_path)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('heart', models.ManyToManyField(blank=True, related_name='hearts', to='users.UserStudent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.UserStudent')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('roomatePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='students.RoommatePost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentedstudent', to='users.UserStudent')),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreply', to='students.PostComment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repliedstudent', to='users.UserStudent')),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
