# Generated by Django 2.2.5 on 2020-09-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROPERTY',
            fields=[
                ('property_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.IntegerField()),
                ('property_name', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('property_status', models.CharField(max_length=10)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserLandLord')),
            ],
        ),
        migrations.CreateModel(
            name='MEDIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_path', models.TextField()),
                ('media_type', models.CharField(max_length=10)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('s_id', models.CharField(max_length=10)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PROPERTY')),
            ],
        ),
    ]
