# Generated by Django 2.2.5 on 2020-09-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200927_1138'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dislikes',
            field=models.ManyToManyField(related_name='propDislikes', to='users.UserStudent'),
        ),
        migrations.AddField(
            model_name='property',
            name='likes',
            field=models.ManyToManyField(related_name='propLikes', to='users.UserStudent'),
        ),
    ]
