# Generated by Django 2.2.5 on 2020-08-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='s_id',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='l_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.LANDLORD', to_field='user_id'),
        ),
    ]
