# Generated by Django 3.1.2 on 2020-12-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='imageDescription',
        ),
    ]
