# Generated by Django 2.2.5 on 2020-09-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200927_1138'),
        ('property', '0002_auto_20200930_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='propDislikes', to='users.UserStudent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='propLikes', to='users.UserStudent'),
        ),
        migrations.CreateModel(
            name='PostQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('propKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserStudent')),
            ],
        ),
        migrations.CreateModel(
            name='PostAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.PostQuestion')),
            ],
        ),
    ]
