# Generated by Django 3.1.2 on 2021-01-09 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_propertyimage_imagedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rentPerPerson',
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.IntegerField(default=0, help_text='Amount in $', validators=[django.core.validators.MinValueValidator(0, 'Minimum Price cannot be lower than 0')], verbose_name='Total Rent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(help_text='Available Rooms', validators=[django.core.validators.MinValueValidator(1, 'Minimum 1'), django.core.validators.MaxValueValidator(20, 'Maximum 20')], verbose_name='Bedrooms'),
        ),
    ]
