# Generated by Django 3.1.2 on 2021-01-14 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20210109_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.FloatField(blank=True, help_text='Total Square feet of property', null=True, validators=[django.core.validators.MinValueValidator(1, 'Square Feet should be atleast 1.')], verbose_name='Square Feet'),
        ),
    ]
