# Generated by Django 2.2.5 on 2020-08-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200831_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_updates',
        ),
    ]
