# Generated by Django 2.2.5 on 2020-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200930_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
