# Generated by Django 2.2.5 on 2020-08-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_property_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
