# Generated by Django 2.2.5 on 2020-09-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200930_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestion',
            name='propKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property', verbose_name='Property'),
        ),
    ]
