# Generated by Django 2.2.5 on 2020-10-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200930_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postquestion',
            options={'ordering': ['-createdDate']},
        ),
    ]
